apiVersion: v1
kind: Namespace
metadata:
  name: grpc-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: grpc-lb
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
      - name: user-grpc
        image: ginuerzh/user-svc:0.0.3
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8000"]
        livenessProbe:
          periodSeconds: 10
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8000"]
      - name: user-gw
        image: ginuerzh/user-svc:0.0.3
        imagePullPolicy: Always
        command:
        - /bin/user-gw
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: grpc-lb
spec:
  clusterIP: None
  selector:
    app: user
  ports:
  - name: grpc
    port: 8000
    targetPort: grpc
  - name: web
    port: 8080
    targetPort: web
